<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>cero.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*" />
    <PackageReference Include="Moq" Version="4.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.*" />
    <PackageReference Include="FluentAssertions" Version="7.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\cero.Core\cero.Core.csproj" />
    <ProjectReference Include="..\..\src\cero.Application\cero.Application.csproj" />
    <ProjectReference Include="..\..\src\cero.EntityFrameworkCore\cero.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
